[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "osi"
version = "0.1.0"
description = "OpensourceID for Google Earth Engine collection for analysis of landcover, forest canopy density, hansen historical forest analysis, slope analysis, and more"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Iqbal Firdaus Kribo", email = "muh.firdausiqbal@gmail.com" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: GIS",
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }

[tool.setuptools.packages.find]
include = ["osi*"]
